In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('data/grades.csv')
df.head(2)

,student_id,assignment1_grade,assignment1_submission,assignment2_grade,assignment2_submission,assignment3_grade,assignment3_submission,assignment4_grade,assignment4_submission,assignment5_grade,assignment5_submission,assignment6_grade,assignment6_submission
0,B73F2C11-70F0-E37D-8B10-1D20AFED50B1,92.733946,2015-11-02 06:55:34.282000000,83.030552,2015-11-09 02:22:58.938000000,67.164441,2015-11-12 08:58:33.998000000,53.011553,2015-11-16 01:21:24.663000000,47.710398,2015-11-20 13:24:59.692000000,38.168318,2015-11-22 18:31:15.934000000
1,98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1,86.790821,2015-11-29 14:57:44.429000000,86.290821,2015-12-06 17:41:18.449000000,69.772657,2015-12-10 08:54:55.904000000,55.098125,2015-12-13 17:32:30.941000000,49.588313,2015-12-19 23:26:39.285000000,44.629482,2015-12-21 17:07:24.275000000

In [7]:
df1 = df.iloc[:,[0,1,3,5]]
df1.head(2)

# this gives us columns at listed indices... easier than typing out long names and using .loc

,student_id,assignment1_grade,assignment2_grade,assignment3_grade
0,B73F2C11-70F0-E37D-8B10-1D20AFED50B1,92.733946,83.030552,67.164441
1,98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1,86.790821,86.290821,69.772657

In [9]:
# Let's assume grade3 is a final test and it counts double

df1.apply(lambda z: print(type(z)))

# What does this give you? A Series for each column....

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

student_id           None
assignment1_grade    None
assignment2_grade    None
assignment3_grade    None
dtype: object

In [11]:
df1.apply(lambda z: print(len(z)))

2315
2315
2315
2315

student_id           None
assignment1_grade    None
assignment2_grade    None
assignment3_grade    None
dtype: object

In [12]:
# We want to sum across rows, and make final score equal to twice the score:

df1.apply(lambda row: row[1] + row[2] + (2*row[3]), axis=1)

0       310.093381
1       312.626955
2       307.845148
3       278.739354
4       200.170504
5       265.204927
6       269.496131
7       283.627837
8       216.201640
9       225.229353
10      169.603484
11      283.790737
12      341.492059
13      264.292971
14      294.106023
15       54.034570
16      156.507000
17      203.549861
18      186.765337
19      134.729226
20      267.229961
21      292.794335
22      288.471609
23      369.581883
24      328.300205
25      292.924348
26      301.443966
27      302.925715
28      377.650016
29      279.874948
           ...
2285    322.705392
2286    353.924801
2287    194.326542
2288    308.574011
2289    286.825038
2290    280.379323
2291    353.106219
2292    278.886364
2293    241.204105
2294    245.050200
2295    139.639091
2296    247.878328
2297    310.055455
2298    229.030369
2299    200.104972
2300    273.436080
2301    274.762308
2302    223.373790
2303    314.976767
2304    201.123151
2305    261.506382
2306    162.168792
2307    332.977067
2308    271.668493
2309    255.076044
2310    287.433060
2311    232.677038
2312    249.436173
2313    349.073465
2314    289.325177
Length: 2315, dtype: float64

In [17]:
# Now to get the average, divide by 400 (total points):
# 'row' here is the parameter function
# ** axis=1 is what tells us to add across rows instead of columns
# by default... axis will set to 0 and that sums (or does whatever) down columns, axis = 1 goes across rows

df1['final'] = df1.apply(lambda row: (row[1] + row[2] + (2*row[3]))/400, axis=1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
df1.head(2)

,student_id,assignment1_grade,assignment2_grade,assignment3_grade,final
0,B73F2C11-70F0-E37D-8B10-1D20AFED50B1,92.733946,83.030552,67.164441,0.775233
1,98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1,86.790821,86.290821,69.772657,0.781567

In [18]:
# want to find top 1% of class:

num_students = int(len(df) * .01)
num_students

23

In [25]:
# this will sort students by score:

indices = df1.final.argsort()
indices.head()

0    1424
1      15
2     226
3    2237
4     339
Name: final, dtype: int64

In [24]:
# see the first person (1424) that is in the list... they are the lowest scoring person:

df1.final[1424]

0.13341549732972496

In [26]:
df1.iloc[indices]

# this is now sorted from lowest to highest

,student_id,assignment1_grade,assignment2_grade,assignment3_grade,final
1424,EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,14.423297,12.980967,12.980967,0.133415
15,24827B50-2FC2-E4B0-E2A0-1989E17749B3,14.959603,14.459603,12.307682,0.135086
226,DDE0526B-7DA4-80E8-C2A6-D097F3826029,18.018145,16.216331,14.594698,0.158560
2237,247B105C-2067-A7AA-2CBE-B65278128C96,19.524002,15.259202,14.453282,0.159224
339,6D2AB78F-44F4-2E8B-5C5E-B79119BC7EAC,18.962538,17.066284,17.066284,0.175403
1929,2B806EF6-A590-1C00-F0C5-1469E3B2152E,18.504458,18.004458,16.924012,0.175892
897,1F51E050-78F7-F270-1B90-ED1BC0376763,19.947190,17.522471,18.222471,0.184787
461,25197F10-E9E9-4C50-63F8-6C896975AAE2,26.812803,21.450242,19.305218,0.217184
973,247B105C-2067-A7AA-2CBE-B65278128C96,24.951796,22.456616,20.210955,0.219576
1010,25197F10-E9E9-4C50-63F8-6C896975AAE2,28.866059,23.092847,18.474277,0.222269
1711,2B806EF6-A590-1C00-F0C5-1469E3B2152E,26.807370,24.126633,19.301306,0.223842
1448,5AB0D44C-86FF-2DE6-B096-B0F5D029E430,29.946373,23.957098,19.165679,0.230587
1966,EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,28.500716,22.800573,20.520515,0.230856
1047,DDE0526B-7DA4-80E8-C2A6-D097F3826029,27.695985,24.496386,20.337109,0.232166
2098,247B105C-2067-A7AA-2CBE-B65278128C96,26.671933,24.004740,21.604266,0.234713
269,EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,30.789082,24.271265,20.157012,0.238436
669,DDE0526B-7DA4-80E8-C2A6-D097F3826029,26.895100,23.775590,24.475590,0.249055
578,25197F10-E9E9-4C50-63F8-6C896975AAE2,30.336421,27.302779,21.842223,0.253309
2094,DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2,33.716586,26.973268,21.578615,0.259618
1096,25197F10-E9E9-4C50-63F8-6C896975AAE2,33.777233,27.021786,21.617429,0.260085
826,247B105C-2067-A7AA-2CBE-B65278128C96,32.596328,25.717063,23.865356,0.265110
1847,EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,30.262783,30.262783,24.210226,0.272365
2191,DDE0526B-7DA4-80E8-C2A6-D097F3826029,35.528671,28.422936,22.738349,0.273571
2140,DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2,35.605615,28.124492,23.239593,0.275523
108,2B806EF6-A590-1C00-F0C5-1469E3B2152E,29.063922,28.563922,26.427530,0.276207
364,EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,33.267674,29.510907,24.348726,0.278690
1030,6D2AB78F-44F4-2E8B-5C5E-B79119BC7EAC,31.336215,30.836215,25.408972,0.282476
100,E0DBCF79-2C64-F398-E68A-6BE4F96653C3,36.553994,28.883195,23.846556,0.282826
1364,25197F10-E9E9-4C50-63F8-6C896975AAE2,36.788520,29.430816,23.544653,0.283272
1765,247B105C-2067-A7AA-2CBE-B65278128C96,31.019540,27.917586,27.917586,0.286931
...,...,...,...,...,...
28,DDE0526B-7DA4-80E8-C2A6-D097F3826029,94.437504,93.937504,94.637504,0.944125
2228,1F51E050-78F7-F270-1B90-ED1BC0376763,99.411631,99.411631,89.470468,0.944410
206,DDE0526B-7DA4-80E8-C2A6-D097F3826029,94.506546,94.006546,94.706546,0.944815
347,2B806EF6-A590-1C00-F0C5-1469E3B2152E,99.461608,99.461608,89.515447,0.944885
610,6D2AB78F-44F4-2E8B-5C5E-B79119BC7EAC,99.474553,98.974553,89.797098,0.945108
234,DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2,94.548222,94.048222,94.748222,0.945232
487,2B806EF6-A590-1C00-F0C5-1469E3B2152E,94.837048,94.337048,95.037048,0.948120
895,5AB0D44C-86FF-2DE6-B096-B0F5D029E430,99.835987,99.835987,89.852389,0.948442
1815,247B105C-2067-A7AA-2CBE-B65278128C96,95.251208,94.751208,95.451208,0.952262
1284,247B105C-2067-A7AA-2CBE-B65278128C96,95.271325,95.271325,95.271325,0.952713
459,25197F10-E9E9-4C50-63F8-6C896975AAE2,95.425696,94.925696,95.625696,0.954007
1319,DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2,95.511848,95.011848,95.711848,0.954868
58,25197F10-E9E9-4C50-63F8-6C896975AAE2,95.568756,95.068756,95.768756,0.955438
198,1F51E050-78F7-F270-1B90-ED1BC0376763,95.718485,95.718485,95.718485,0.957185
667,DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2,95.944829,95.444829,96.144829,0.959198
86,42A3C4F0-7032-7368-2D67-989735754020,96.219108,96.219108,96.219108,0.962191
1960,5AB0D44C-86FF-2DE6-B096-B0F5D029E430,96.478922,95.978922,96.678922,0.964539
1630,247B105C-2067-A7AA-2CBE-B65278128C96,96.819632,96.819632,96.819632,0.968196
1229,DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2,96.982689,96.482689,97.182689,0.969577
1218,25197F10-E9E9-4C50-63F8-6C896975AAE2,97.087879,97.087879,97.087879,0.970879
881,1F51E050-78F7-F270-1B90-ED1BC0376763,97.277300,96.777300,97.477300,0.972523
903,247B105C-2067-A7AA-2CBE-B65278128C96,97.388763,96.888763,97.588763,0.973638
2160,6D2AB78F-44F4-2E8B-5C5E-B79119BC7EAC,97.473243,96.973243,97.673243,0.974482
1099,6D2AB78F-44F4-2E8B-5C5E-B79119BC7EAC,97.571739,97.571739,97.571739,0.975717
300,DDE0526B-7DA4-80E8-C2A6-D097F3826029,97.604671,97.604671,97.604671,0.976047
1174,2B806EF6-A590-1C00-F0C5-1469E3B2152E,97.952182,97.452182,98.152182,0.979272
585,EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,99.134693,99.134693,99.134693,0.991347
376,1F51E050-78F7-F270-1B90-ED1BC0376763,99.435672,98.935672,99.635672,0.994107
619,2B806EF6-A590-1C00-F0C5-1469E3B2152E,99.455813,98.955813,99.655813,0.994308
369,DDE0526B-7DA4-80E8-C2A6-D097F3826029,99.581715,99.581715,99.581715,0.995817

In [27]:
df1.iloc[indices[-num_students:]]

# this gets just the last 23 students, who scored the highest

,student_id,assignment1_grade,assignment2_grade,assignment3_grade,final
895,5AB0D44C-86FF-2DE6-B096-B0F5D029E430,99.835987,99.835987,89.852389,0.948442
1815,247B105C-2067-A7AA-2CBE-B65278128C96,95.251208,94.751208,95.451208,0.952262
1284,247B105C-2067-A7AA-2CBE-B65278128C96,95.271325,95.271325,95.271325,0.952713
459,25197F10-E9E9-4C50-63F8-6C896975AAE2,95.425696,94.925696,95.625696,0.954007
1319,DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2,95.511848,95.011848,95.711848,0.954868
58,25197F10-E9E9-4C50-63F8-6C896975AAE2,95.568756,95.068756,95.768756,0.955438
198,1F51E050-78F7-F270-1B90-ED1BC0376763,95.718485,95.718485,95.718485,0.957185
667,DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2,95.944829,95.444829,96.144829,0.959198
86,42A3C4F0-7032-7368-2D67-989735754020,96.219108,96.219108,96.219108,0.962191
1960,5AB0D44C-86FF-2DE6-B096-B0F5D029E430,96.478922,95.978922,96.678922,0.964539
1630,247B105C-2067-A7AA-2CBE-B65278128C96,96.819632,96.819632,96.819632,0.968196
1229,DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2,96.982689,96.482689,97.182689,0.969577
1218,25197F10-E9E9-4C50-63F8-6C896975AAE2,97.087879,97.087879,97.087879,0.970879
881,1F51E050-78F7-F270-1B90-ED1BC0376763,97.277300,96.777300,97.477300,0.972523
903,247B105C-2067-A7AA-2CBE-B65278128C96,97.388763,96.888763,97.588763,0.973638
2160,6D2AB78F-44F4-2E8B-5C5E-B79119BC7EAC,97.473243,96.973243,97.673243,0.974482
1099,6D2AB78F-44F4-2E8B-5C5E-B79119BC7EAC,97.571739,97.571739,97.571739,0.975717
300,DDE0526B-7DA4-80E8-C2A6-D097F3826029,97.604671,97.604671,97.604671,0.976047
1174,2B806EF6-A590-1C00-F0C5-1469E3B2152E,97.952182,97.452182,98.152182,0.979272
585,EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,99.134693,99.134693,99.134693,0.991347
376,1F51E050-78F7-F270-1B90-ED1BC0376763,99.435672,98.935672,99.635672,0.994107
619,2B806EF6-A590-1C00-F0C5-1469E3B2152E,99.455813,98.955813,99.655813,0.994308
369,DDE0526B-7DA4-80E8-C2A6-D097F3826029,99.581715,99.581715,99.581715,0.995817

In [30]:
filtered_students = df1.iloc[indices[-num_students:]][::-1]
filtered_students

# this reverses to get students in order from highest score to lowest

,student_id,assignment1_grade,assignment2_grade,assignment3_grade,final
369,DDE0526B-7DA4-80E8-C2A6-D097F3826029,99.581715,99.581715,99.581715,0.995817
619,2B806EF6-A590-1C00-F0C5-1469E3B2152E,99.455813,98.955813,99.655813,0.994308
376,1F51E050-78F7-F270-1B90-ED1BC0376763,99.435672,98.935672,99.635672,0.994107
585,EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,99.134693,99.134693,99.134693,0.991347
1174,2B806EF6-A590-1C00-F0C5-1469E3B2152E,97.952182,97.452182,98.152182,0.979272
300,DDE0526B-7DA4-80E8-C2A6-D097F3826029,97.604671,97.604671,97.604671,0.976047
1099,6D2AB78F-44F4-2E8B-5C5E-B79119BC7EAC,97.571739,97.571739,97.571739,0.975717
2160,6D2AB78F-44F4-2E8B-5C5E-B79119BC7EAC,97.473243,96.973243,97.673243,0.974482
903,247B105C-2067-A7AA-2CBE-B65278128C96,97.388763,96.888763,97.588763,0.973638
881,1F51E050-78F7-F270-1B90-ED1BC0376763,97.277300,96.777300,97.477300,0.972523
1218,25197F10-E9E9-4C50-63F8-6C896975AAE2,97.087879,97.087879,97.087879,0.970879
1229,DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2,96.982689,96.482689,97.182689,0.969577
1630,247B105C-2067-A7AA-2CBE-B65278128C96,96.819632,96.819632,96.819632,0.968196
1960,5AB0D44C-86FF-2DE6-B096-B0F5D029E430,96.478922,95.978922,96.678922,0.964539
86,42A3C4F0-7032-7368-2D67-989735754020,96.219108,96.219108,96.219108,0.962191
667,DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2,95.944829,95.444829,96.144829,0.959198
198,1F51E050-78F7-F270-1B90-ED1BC0376763,95.718485,95.718485,95.718485,0.957185
58,25197F10-E9E9-4C50-63F8-6C896975AAE2,95.568756,95.068756,95.768756,0.955438
1319,DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2,95.511848,95.011848,95.711848,0.954868
459,25197F10-E9E9-4C50-63F8-6C896975AAE2,95.425696,94.925696,95.625696,0.954007
1284,247B105C-2067-A7AA-2CBE-B65278128C96,95.271325,95.271325,95.271325,0.952713
1815,247B105C-2067-A7AA-2CBE-B65278128C96,95.251208,94.751208,95.451208,0.952262
895,5AB0D44C-86FF-2DE6-B096-B0F5D029E430,99.835987,99.835987,89.852389,0.948442

In [31]:
filtered_students.student_id.values

# this gives us just the student id's of those students

array(['DDE0526B-7DA4-80E8-C2A6-D097F3826029',
       '2B806EF6-A590-1C00-F0C5-1469E3B2152E',
       '1F51E050-78F7-F270-1B90-ED1BC0376763',
       'EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31',
       '2B806EF6-A590-1C00-F0C5-1469E3B2152E',
       'DDE0526B-7DA4-80E8-C2A6-D097F3826029',
       '6D2AB78F-44F4-2E8B-5C5E-B79119BC7EAC',
       '6D2AB78F-44F4-2E8B-5C5E-B79119BC7EAC',
       '247B105C-2067-A7AA-2CBE-B65278128C96',
       '1F51E050-78F7-F270-1B90-ED1BC0376763',
       '25197F10-E9E9-4C50-63F8-6C896975AAE2',
       'DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2',
       '247B105C-2067-A7AA-2CBE-B65278128C96',
       '5AB0D44C-86FF-2DE6-B096-B0F5D029E430',
       '42A3C4F0-7032-7368-2D67-989735754020',
       'DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2',
       '1F51E050-78F7-F270-1B90-ED1BC0376763',
       '25197F10-E9E9-4C50-63F8-6C896975AAE2',
       'DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2',
       '25197F10-E9E9-4C50-63F8-6C896975AAE2',
       '247B105C-2067-A7AA-2CBE-B65278128C96',
       '247B105C-2067-A7AA-2CBE-B65278128C96',
       '5AB0D44C-86FF-2DE6-B096-B0F5D029E430'], dtype=object)